import React from 'react';

export const metadata = {
  title: 'Terms & Conditions | N.S. INTERIOR',
  description: 'Terms and conditions for N.S. INTERIOR execution services and estimate calculator.',
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-6 text-slate-300 text-xs sm:text-sm leading-relaxed">
      <h1 className="text-3xl font-extrabold text-white">Terms & Conditions</h1>
      <p className="text-slate-400">Effective Date: January 1, 2026</p>

      <h2 className="text-xl font-bold text-white pt-4">1. Scope of Services</h2>
      <p>
        N.S. INTERIOR is an interior execution and contracting business. We provide site work including modular kitchens, carpentry, false ceiling, painting, electrical, plumbing, tiling, and full renovations.
      </p>

      <h2 className="text-xl font-bold text-white pt-4">2. Estimate Calculator Disclaimer</h2>
      <p>
        All prices generated by the website Estimate Calculator are baseline <strong>APPROXIMATE ESTIMATES ONLY</strong>. They do NOT constitute a binding final quotation. Binding quotations are issued only after physical on-site measurements and material selection.
      </p>

      <h2 className="text-xl font-bold text-white pt-4">3. Quotations & Payments</h2>
      <p>
        Official project quotations are provided in writing after site visits. Payment schedules and milestone terms will be detailed in the project contract prior to execution start.
      </p>
    </div>
  );
}
